apiVersion: v1
kind: Deployment
metadata:
  name: mongodb-delpoy
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchlabels: 
      app: mongodb
  templates:
    metadata: 
      labels: 
        app: mongodb
    spec:
      conatiners: 
      - name: mongodb
        image: mongo
        ports: 
        - containerPort: "27017"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: 