apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: 
  mg-root-username: dXNlcm5hbWU=
  mg-root-password: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret1
type: Opaque
data: 
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
  